#!/bin/bash

set -xe
shopt -s nullglob

I2C=
for dev in /sys/devices/pci0000:00/0000:00:1f.4/i2c-*; do
  I2C=$(basename $dev i2c-)
  I2C=${I2C/i2c-/}
done

if [[ -z "$I2C" ]]; then
  echo "Cannot find I2C"
  exit 1
fi

# 0x58: dimm0
# 0x59: dimm1
# 0x5a: dimm2
# 0x5b: dimm3
DIMM="0x5b"

COLOR_WHITE="255 255 255 255"
COLOR_RED="255 0 0 255"
COLOR_GREEN="0 255 0 255"
COLOR_BLUE="0 0 255 255"
COLOR_GRAY="128 128 128 255"
COLOR_BLACK="0 0 0 0"

write() {
  i2cset -y "$I2C" "$DIMM" "$@"
}

dump() {
  i2cdump -y "$I2C" "$DIMM"
}

write_multi() {
  ADDR="$1"
  shift
  for param; do
    write "$ADDR" "$param"
  done 
}

write_bright() {
  write 16 "$@"
}

write_leds() {
  if [[ $# -ne 10 ]]; then
    echo "write_leds requires exactly 10 leds"
    return 1
  fi

  write 33 0
  write_multi 32 $@
}

write_config() {
  if [[ $# -lt 4 ]]; then
    echo "usage: $0 <style> <speed> <color-type> <direction> [rgba1] [rgba2]"
    return 1
  fi

  write 130 2
  sleep 1s
  write 33 0
  write_multi 32 $@
  write 130 1
  sleep 1s
  write 192 0
}

write_bright 20

write_leds "$COLOR_WHITE" \
  "$COLOR_BLACK" \
  "$COLOR_BLACK" \
  "$COLOR_WHITE" \
  "$COLOR_BLACK" \
  "$COLOR_BLACK" \
  "$COLOR_WHITE" \
  "$COLOR_BLACK" \
  "$COLOR_BLACK" \
  "$COLOR_WHITE"

# style:
# - 0?
# - rainbow: 3, random
# - spiral rainbow: 2, random
# - visor: 5, random or alternating rgba1/2
# - rain: 6, random or alternating rgba1/2
# - rain alternating: 4, random or alternating rgba1/2
# - breathing: 1, random
# - color shift: 8, random
# - marquee: 7, random, single color
# - color pulse: 10, single color
# - user: 16
#
# color type:
# - random: 0
# - alternating: 1
#
# speed:
# - 0 - low
# - 1 - medium
# - 2 - high

# rainbow
# write_config 3 1 0 0 "$COLOR_BLACK" "$COLOR_BLACK"

# rain
write_config 16 1 1 0 "$COLOR_BLUE" "$COLOR_RED"

