#!/bin/bash

ALPHA=255

source $(dirname $(readlink -f "$0"))/functions/common-functions
source $(dirname $(readlink -f "$0"))/functions/corsair-functions

if [[ $# -ne 12 ]]; then
  echo "usage: $0 <dimm> <brightness> <10 colors>"
  exit 1
fi

set_dimm "$1"
retry write_bright "$2"
shift 2

retry write_leds "$@"
retry write_config 16 0 0 0
