#!/bin/bash

source $(dirname $(readlink -f "$0"))/functions/common-functions
source $(dirname $(readlink -f "$0"))/functions/msi-functions

STYLE=0x9f
DATA=0
E0=2
ONTIME=5
OFFTIME=20
DARKTIME=20
COLOR="red"
MASK=0

usage() {
  cat <<EOF
usage: $0 [options]

mask:
  all, jrgb1, bot, audio1, audio2, audio3, audio4, pch

mode:
  breathing, flashing, marque, meteor,
  mystic, rainbow, lighting, dual-blink,
  off

color:
  color=<name-of-color>: main color (default red, sometimes random)

extra:
  range=?
  ontime=5,10,15,20 (breathing, flashing, dual-blink)
  offtime=5,10,15,20 (flashing, dual-blink)
  darktime=5,10,15,20 (dual-blink)

examples:
  \$ $0 all rainbow
  \$ $0 static pch color=white
EOF
}

for arg; do
  case "$arg" in
    all)
      MASK=255
      ;;

    jrgb1)
      MASK=$((MASK+1))
      ;;

    bot)
      MASK=$((MASK+2))
      ;;

    audio1)
      MASK=$((MASK+4))
      ;;

    audio2)
      MASK=$((MASK+8))
      ;;

    audio3)
      MASK=$((MASK+16))
      ;;

    audio4)
      MASK=$((MASK+32))
      ;;

    pch)
      MASK=$((MASK+64))
      ;;

    breathing)
      STYLE=0x90
      ;;

    flashing)
      STYLE=0x91
      ;;

    marque)
      STYLE=0x92
      ;;

    meteor)
      STYLE=0x93
      ;;

    mystick)
      STYLE=0x94
      ;;

    rainbow)
      STYLE=0x95
      ;;

    lighting)
      STYLE=0x96
      ;;

    dual-blink)
      STYLE=0x99
      DATA=1
      ;;

    static)
      STYLE=0x9f
      DATA=1
      ;;

    color=*)
      COLOR=${arg/color=/}
      ;;

    range=[0-9]*)
      DATA=${arg/range=/}
      ;;

    ontime=[0-9]*)
      ONTIME=${arg/ontime=/}
      ;;

    offtime=[0-9]*)
      OFFTIME=${arg/offtime=/}
      ;;

    darktime=[0-9]*)
      DARKTIME=${arg/darktime=/}
      ;;

    off)
      STYLE=0x9f
      DATA=0
      ;;

    help)
      usage
      exit 1
      ;;

    *)
      echo "unknown argument: $arg"
      usage
      exit 1
      ;;
  esac
done

COLOR=$(get_color $COLOR)

write_mono_mask 0 0
write_mask $MASK 0 0 0
write_rgb $COLOR
write_cmd $STYLE $DATA $E0 $ONTIME $OFFTIME 0 $DARKTIME
